In [1]:
import requests
from io import BytesIO
import pandas as pd
pd.set_option('display.max_columns', None)

In [9]:
url = 'https://www.dubaipulse.gov.ae/dataset/3b25a6f5-9077-49d7-8a1e-bc6d5dea88fd/resource/a37511b0-ea36-485d-bccd-2d6cb24507e7/download/transactions.csv'
r1 = requests.get(url)
tr = pd.read_csv(BytesIO(r1.content))
tr = tr[tr["property_type_en"]=="Unit"].sort_values("instance_date", ascending=False)

In [13]:
url2 = 'https://www.dubaipulse.gov.ae/dataset/85462a5b-08dc-4325-9242-676a0de4afc4/resource/7d4deadf-c9bc-47a4-85de-998d0ce38bf3/download/units.csv'
r2 = requests.get(url2)
un = pd.read_csv(BytesIO(r2.content))

/tmp/ipykernel_26130/2322835276.py:3: DtypeWarning: Columns (3,4,7,10,12,13,16,18,19,22,23,25,26,29,36,38,39,41,42,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  un = pd.read_csv(BytesIO(r2.content))

In [20]:
tr.columns

Index(['transaction_id', 'procedure_id', 'trans_group_id', 'trans_group_ar',
       'trans_group_en', 'procedure_name_ar', 'procedure_name_en',
       'instance_date', 'property_type_id', 'property_type_ar',
       'property_type_en', 'property_sub_type_id', 'property_sub_type_ar',
       'property_sub_type_en', 'property_usage_ar', 'property_usage_en',
       'reg_type_id', 'reg_type_ar', 'reg_type_en', 'area_id', 'area_name_ar',
       'area_name_en', 'building_name_ar', 'building_name_en',
       'project_number', 'project_name_ar', 'project_name_en',
       'master_project_en', 'master_project_ar', 'nearest_landmark_ar',
       'nearest_landmark_en', 'nearest_metro_ar', 'nearest_metro_en',
       'nearest_mall_ar', 'nearest_mall_en', 'rooms_ar', 'rooms_en',
       'has_parking', 'procedure_area', 'actual_worth', 'meter_sale_price',
       'rent_value', 'meter_rent_price', 'no_of_parties_role_1',
       'no_of_parties_role_2', 'no_of_parties_role_3'],
      dtype='object')

In [14]:
un.columns

Index(['property_id', 'area_id', 'zone_id', 'area_name_ar', 'area_name_en',
       'land_number', 'land_sub_number', 'building_number', 'unit_number',
       'unit_balcony_area', 'unit_parking_number', 'parking_allocation_type',
       'parking_allocation_type_ar', 'parking_allocation_type_en',
       'common_area', 'actual_common_area', 'floor', 'rooms', 'rooms_ar',
       'rooms_en', 'actual_area', 'property_type_id', 'property_type_ar',
       'property_type_en', 'property_sub_type_id', 'property_sub_type_ar',
       'property_sub_type_en', 'parent_property_id', 'grandparent_property_id',
       'creation_date', 'munc_zip_code', 'munc_number', 'parcel_id',
       'is_free_hold', 'is_lease_hold', 'is_registered',
       'pre_registration_number', 'master_project_id', 'master_project_en',
       'master_project_ar', 'project_id', 'project_name_ar', 'project_name_en',
       'land_type_id', 'land_type_ar', 'land_type_en'],
      dtype='object')

In [14]:
tr[tr["reg_type_id"]!=0].head()

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,property_type_en,property_sub_type_id,property_sub_type_ar,property_sub_type_en,property_usage_ar,property_usage_en,reg_type_id,reg_type_ar,reg_type_en,area_id,area_name_ar,area_name_en,building_name_ar,building_name_en,project_number,project_name_ar,project_name_en,master_project_en,master_project_ar,nearest_landmark_ar,nearest_landmark_en,nearest_metro_ar,nearest_metro_en,nearest_mall_ar,nearest_mall_en,rooms_ar,rooms_en,has_parking,procedure_area,actual_worth,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3
111193,1-11-2021-23524,11,1,مبايعات,Sales,بيع,Sell,31-12-2021,3,وحدة,Unit,60.0,شقه سكنيه,Flat,سكني,Residential,1,العقارات القائمة,Existing Properties,409,البرشاء جنوب الثالثة,Al Barshaa South Third,سامانا جرينز,SAMANA GREENS,2032.0,سامانا كرين,Samana Green,Arjan,أرجان,موتور سيتي,Motor City,محطة مترو شرف دي جي,Sharaf Dg Metro Station,مول الإمارات,Mall of the Emirates,استوديو,Studio,1,43.59,328517.0,7536.53,NaN,NaN,1.0,1.0,0.0
814279,1-41-2020-7872,41,1,مبايعات,Sales,بيع مبدئى,Delayed Sell,31-12-2020,3,وحدة,Unit,60.0,شقه سكنيه,Flat,سكني,Residential,1,العقارات القائمة,Existing Properties,485,معيصم الأول,Me'Aisem First,دانية 3,DANIA 3,1731.0,ميدتاون - دنيا,MIDTOWN - DANIA,International Media Production Zone,المنطقة العالمية للإنتاج الإعلامي,أكاديمية المدينة الرياضية للسباحة,Sports City Swimming Academy,برج هاربور,Harbour Tower,ابن بطوطة مول,Ibn-e-Battuta Mall,استوديو,Studio,1,40.96,510201.0,12456.08,NaN,NaN,1.0,1.0,0.0
513378,1-11-2020-13171,11,1,مبايعات,Sales,بيع,Sell,31-12-2020,3,وحدة,Unit,60.0,شقه سكنيه,Flat,سكني,Residential,1,العقارات القائمة,Existing Properties,409,البرشاء جنوب الثالثة,Al Barshaa South Third,B-ذ ونغس,The Wings - B,1948.0,ذ ونغس,THE WINGS,Arjan,أرجان,موتور سيتي,Motor City,محطة مترو شرف دي جي,Sharaf Dg Metro Station,مول الإمارات,Mall of the Emirates,غرفتين,2 B/R,1,111.40,900000.0,8078.99,NaN,NaN,1.0,1.0,0.0
133840,1-11-2020-13245,11,1,مبايعات,Sales,بيع,Sell,31-12-2020,3,وحدة,Unit,60.0,شقه سكنيه,Flat,سكني,Residential,1,العقارات القائمة,Existing Properties,526,الخليج التجارى,Business Bay,ايليت بزنس باي ريذيدنس,Elite Business Bay Residence,1868.0,اليت بزنس باي ريذيدنس,ELITE BUSINESS BAY RESIDENCE,Business Bay,الخليج التجاري,وسط مدينة دبي,Downtown Dubai,محطة مترو الخليج التجاري,Business Bay Metro Station,مول دبي,Dubai Mall,استوديو,Studio,1,46.99,597600.0,12717.60,NaN,NaN,1.0,1.0,0.0
370800,1-11-2020-13239,11,1,مبايعات,Sales,بيع,Sell,31-12-2020,3,وحدة,Unit,60.0,شقه سكنيه,Flat,سكني,Residential,1,العقارات القائمة,Existing Properties,409,البرشاء جنوب الثالثة,Al Barshaa South Third,B-ذ ونغس,The Wings - B,1948.0,ذ ونغس,THE WINGS,Arjan,أرجان,موتور سيتي,Motor City,محطة مترو شرف دي جي,Sharaf Dg Metro Station,مول الإمارات,Mall of the Emirates,غرفة,1 B/R,1,73.99,550000.0,7433.44,NaN,NaN,1.0,1.0,0.0

In [19]:
un.head()

,property_id,area_id,zone_id,area_name_ar,area_name_en,land_number,land_sub_number,building_number,unit_number,unit_balcony_area,unit_parking_number,parking_allocation_type,parking_allocation_type_ar,parking_allocation_type_en,common_area,actual_common_area,floor,rooms,rooms_ar,rooms_en,actual_area,property_type_id,property_type_ar,property_type_en,property_sub_type_id,property_sub_type_ar,property_sub_type_en,parent_property_id,grandparent_property_id,creation_date,munc_zip_code,munc_number,parcel_id,is_free_hold,is_lease_hold,is_registered,pre_registration_number,master_project_id,master_project_en,master_project_ar,project_id,project_name_ar,project_name_en,land_type_id,land_type_ar,land_type_en
0,1300000003,351.0,2.0,الثنيه الثالثة,Al Thanyah Third,31.0,0.0,2,207,19.97,"B-63 , B-64",NaN,NaN,NaN,NaN,NaN,2,3.0,ثلاث غرف,3 B/R,191.84,3.0,وحدة,Unit,60.0,شقه سكنيه,Flat,149342.0,87715.0,NaN,388.0,1500.0,3881500.0,1.0,0.0,1.0,NaN,33.0,The Greens,الروضة,NaN,NaN,NaN,1.0,سكنى,Residential
1,1300000004,351.0,2.0,الثنيه الثالثة,Al Thanyah Third,34.0,0.0,1,G01,13.22,B-27,NaN,NaN,NaN,0.40,135.0,G,2.0,غرفتان,2 B/R,126.28,3.0,وحدة,Unit,60.0,شقه سكنيه,Flat,149349.0,87719.0,NaN,388.0,1498.0,3881498.0,1.0,0.0,1.0,NaN,33.0,The Greens,الروضة,NaN,NaN,NaN,1.0,سكنى,Residential
2,1300000005,351.0,2.0,الثنيه الثالثة,Al Thanyah Third,34.0,0.0,1,G02,96.20,B-28,NaN,NaN,NaN,0.74,248.0,G,3.0,ثلاث غرف,3 B/R,231.48,3.0,وحدة,Unit,60.0,شقه سكنيه,Flat,149349.0,87719.0,NaN,388.0,1498.0,3881498.0,1.0,0.0,1.0,NaN,33.0,The Greens,الروضة,NaN,NaN,NaN,1.0,سكنى,Residential
3,1300000006,351.0,2.0,الثنيه الثالثة,Al Thanyah Third,34.0,0.0,1,G03,106.46,B-29,NaN,NaN,NaN,0.77,258.0,G,3.0,ثلاث غرف,3 B/R,240.90,3.0,وحدة,Unit,60.0,شقه سكنيه,Flat,149349.0,87719.0,NaN,388.0,1498.0,3881498.0,1.0,0.0,1.0,NaN,33.0,The Greens,الروضة,NaN,NaN,NaN,1.0,سكنى,Residential
4,1300000007,351.0,2.0,الثنيه الثالثة,Al Thanyah Third,34.0,0.0,1,G04,29.10,"B-34,B-36",NaN,NaN,NaN,0.69,231.0,G,4.0,أربعة غرف,4 B/R,215.76,3.0,وحدة,Unit,60.0,شقه سكنيه,Flat,149349.0,87719.0,NaN,388.0,1498.0,3881498.0,1.0,0.0,1.0,NaN,33.0,The Greens,الروضة,NaN,NaN,NaN,1.0,سكنى,Residential

In [7]:
temp[temp["land_type_en"]=='Residential']

,property_id,area_id,zone_id,area_name_ar,area_name_en,land_number,land_sub_number,building_number,common_area,actual_common_area,floors,rooms,rooms_ar,rooms_en,car_parks,built_up_area,bld_levels,shops,flats,offices,swimming_pools,elevators,actual_area,property_type_id,property_type_ar,property_type_en,property_sub_type_id,property_sub_type_ar,property_sub_type_en,parent_property_id,creation_date,parcel_id,is_free_hold,is_lease_hold,is_registered,pre_registration_number,master_project_id,master_project_en,master_project_ar,project_id,project_name_ar,project_name_en,land_type_id,land_type_ar,land_type_en
2583,1200002648,351,2,الثنيه الثالثة,Al Thanyah Third,237,0,L Hattan 2-V-28,1.31,NaN,3.0,5.0,خمس غرف,5 B/R,2.0,711.56,NaN,NaN,NaN,NaN,NaN,NaN,975.90,2,مبنى,Building,4,فيلا,Villa,97345,NaN,3881123.0,1.0,0.0,1.0,NaN,52.0,Lakes - Hattan II,البحيرات - حتان 2,NaN,NaN,NaN,1.0,سكنى,Residential
2584,1200002649,351,2,الثنيه الثالثة,Al Thanyah Third,282,0,L Hattan 2-V-61,0.95,NaN,3.0,4.0,أربعة غرف,4 B/R,2.0,533.37,NaN,NaN,NaN,NaN,NaN,NaN,707.23,2,مبنى,Building,4,فيلا,Villa,97389,NaN,3881172.0,1.0,0.0,1.0,NaN,52.0,Lakes - Hattan II,البحيرات - حتان 2,NaN,NaN,NaN,1.0,سكنى,Residential
2585,1200002650,351,2,الثنيه الثالثة,Al Thanyah Third,286,0,L Hattan 2-V-13,1.41,NaN,3.0,5.0,خمس غرف,5 B/R,2.0,711.56,NaN,NaN,NaN,NaN,NaN,NaN,1048.59,2,مبنى,Building,4,فيلا,Villa,97392,NaN,3881196.0,1.0,0.0,1.0,NaN,52.0,Lakes - Hattan II,البحيرات - حتان 2,NaN,NaN,NaN,1.0,سكنى,Residential
2586,1200002651,351,2,الثنيه الثالثة,Al Thanyah Third,293,0,L Hattan 2-V-6,1.13,NaN,3.0,4.0,أربعة غرف,4 B/R,2.0,579.61,NaN,NaN,NaN,NaN,NaN,NaN,839.20,2,مبنى,Building,4,فيلا,Villa,97399,NaN,3881204.0,1.0,0.0,1.0,NaN,52.0,Lakes - Hattan II,البحيرات - حتان 2,NaN,NaN,NaN,1.0,سكنى,Residential
4960,1200005035,351,2,الثنيه الثالثة,Al Thanyah Third,316,0,TL Maeen-TH-240,0.36,NaN,2.0,3.0,ثلاث غرف,3 B/R,2.0,249.48,NaN,NaN,NaN,NaN,NaN,NaN,364.73,2,مبنى,Building,4,فيلا,Villa,103027,NaN,3881212.0,1.0,0.0,1.0,NaN,56.0,Lakes - Maeen,البحيرات - معين,NaN,NaN,NaN,1.0,سكنى,Residential
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192392,2800050206,473,1,وادي الشبك,Wadi Alshabak,1402,0,0,NaN,NaN,NaN,5.0,خمسة غرف و صالة,5 bed rooms+hall,6.0,733.00,NaN,NaN,NaN,NaN,NaN,NaN,733.44,2,مبنى,Building,4,فيلا,Villa,405404509,29-03-2024,4314300.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,سكنى,Residential
192397,2800050211,340,2,غدير الطير,Ghadeer Al tair,1184,0,0,NaN,NaN,NaN,5.0,خمسة غرف و صالة,5 bed rooms+hall,2.0,628.00,NaN,NaN,NaN,NaN,NaN,NaN,628.36,2,مبنى,Building,4,فيلا,Villa,324367233,03-04-2024,3555954.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,سكنى,Residential
192404,2800050218,406,2,ند الشبا الرابعه,Nad Al Shiba Fourth,975,0,0,0.00,NaN,0.0,5.0,خمسة غرف و صالة,5 bed rooms+hall,0.0,660.00,NaN,NaN,NaN,NaN,NaN,NaN,660.00,2,مبنى,Building,4,فيلا,Villa,15235119,03-04-2024,6174117.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,سكنى,Residential
192409,2800050223,473,1,وادي الشبك,Wadi Alshabak,1543,0,0,NaN,NaN,NaN,5.0,خمسة غرف و صالة,5 bed rooms+hall,4.0,5000.00,NaN,NaN,NaN,NaN,NaN,NaN,5000.00,2,مبنى,Building,4,فيلا,Villa,476398281,15-04-2024,4318363.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,سكنى,Residential
192410,2800050224,473,1,وادي الشبك,Wadi Alshabak,1434,0,0,NaN,NaN,NaN,5.0,خمسة غرف و صالة,5 bed rooms+hall,2.0,669.00,NaN,NaN,NaN,NaN,NaN,NaN,669.03,2,مبنى,Building,4,فيلا,Villa,430671763,22-04-2024,4317147.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,سكنى,Residential

In [2]:
url3 = 'https://www.dubaipulse.gov.ae/dataset/04168da5-9d10-4fe3-bd29-6dba97751435/resource/6450b4a5-f9c5-4aca-8e64-b38aa8db4c5a/download/buildings.csv'
r3 = requests.get(url3)

In [3]:
temp = pd.read_csv(BytesIO(r3.content))

/tmp/ipykernel_26130/2463982015.py:1: DtypeWarning: Columns (35,37,38,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(BytesIO(r3.content))